# Generated by Django 4.0.4 on 2022-07-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0002_post_mainphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='skills',
            fields=[
                ('nokey', models.AutoField(primary_key=True, serialize=False)),
                ('sn', models.CharField(max_length=50)),
                ('sbs', models.CharField(max_length=50)),
                ('lv', models.CharField(max_length=50)),
            ],
        ),
    ]
