# Generated by Django 4.0.4 on 2022-07-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0003_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='lv',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skills',
            name='sbs',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skills',
            name='sn',
            field=models.CharField(max_length=200),
        ),
    ]
